name = "basic-book"
defaultTargets = ["Book", "generate-book"]

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso"
rev = "v4.29.0"


[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.29.0"

[[lean_lib]]
name = "Book"

[[lean_exe]]
name = "generate-book"
root = "Main"
